import type { Metadata } from "next";
import Script from 'next/script';
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <head>
            <Script
                src="https://umami.nuknal.com/script.js"
                data-website-id="1caa3149-0a7d-46f9-a003-b2beb5eede85"
            />
        </head>
        <body className={inter.className}>{children}</body>
    </html>
  );
}
