import type { Metadata } from "next";
import Script from 'next/script';
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <head>
            <Script
                src="https://umami.nuknal.com/script.js"
                data-website-id="07cdda53-06b3-447c-8c30-1bceab22ac91"
            />
        </head>
        <body className={inter.className}>{children}</body>
    </html>
  );
}
